// Pinned metadata shapes; changes require a reviewed contract version.
package reportmetadata

import "strings"

const Contract = "fec/report-metadata@1.0.0"
const ParserVersion = "legal-tender.fec.report-metadata-review.v1"
const SwaggerSHA256 = "0cca7f2af73270b35d7276e53d99b56b2f8f9970b33cb5d36a85fdb8b773caed"

// All present nulls are retained. Missing fields are a different, blocking state.
var shapes = map[string]map[string]string{
	"/v1/filings/": fieldsByKind(map[string]string{
		"string[]":  "additional_bank_names",
		"integer[]": "amendment_chain",
		"string":    "amendment_indicator bank_depository_city bank_depository_name bank_depository_state bank_depository_street_1 bank_depository_street_2 bank_depository_zip beginning_image_number candidate_id candidate_name committee_id committee_name committee_type coverage_end_date coverage_start_date csv_url document_description document_type document_type_full ending_image_number fec_file_id fec_url form_category form_type html_url means_filed office party pdf_url primary_general_indicator receipt_date report_type report_type_full request_type state sub_id treasurer_name update_date",
		"integer":   "amendment_version cycle election_year file_number most_recent_file_number pages previous_file_number report_year",
		"number":    "cash_on_hand_beginning_period cash_on_hand_end_period debts_owed_by_committee debts_owed_to_committee house_personal_funds net_donations opposition_personal_funds senate_personal_funds total_communication_cost total_disbursements total_independent_expenditures total_individual_contributions total_receipts",
		"boolean":   "is_amended most_recent",
	}),
	"/v1/reports/house-senate/": fieldsByKind(map[string]string{
		"number":          "aggregate_amount_personal_contributions_general aggregate_contributions_personal_funds_primary all_other_loans_period all_other_loans_ytd candidate_contribution_period candidate_contribution_ytd cash_on_hand_beginning_period cash_on_hand_end_period debts_owed_by_committee debts_owed_to_committee gross_receipt_authorized_committee_general gross_receipt_authorized_committee_primary gross_receipt_minus_personal_contribution_general gross_receipt_minus_personal_contributions_primary loan_repayments_candidate_loans_period loan_repayments_candidate_loans_ytd loan_repayments_other_loans_period loan_repayments_other_loans_ytd loans_made_by_candidate_period loans_made_by_candidate_ytd most_recent_file_number net_contributions_period net_contributions_ytd net_operating_expenditures_period net_operating_expenditures_ytd operating_expenditures_period operating_expenditures_ytd other_disbursements_period other_disbursements_ytd other_political_committee_contributions_period other_political_committee_contributions_ytd other_receipts_period other_receipts_ytd political_party_committee_contributions_period political_party_committee_contributions_ytd previous_file_number refunded_individual_contributions_period refunded_individual_contributions_ytd refunded_other_political_committee_contributions_period refunded_other_political_committee_contributions_ytd refunded_political_party_committee_contributions_period refunded_political_party_committee_contributions_ytd refunds_total_contributions_col_total_ytd subtotal_period total_contribution_refunds_col_total_period total_contribution_refunds_period total_contribution_refunds_ytd total_contributions_column_total_period total_contributions_period total_contributions_ytd total_disbursements_period total_disbursements_ytd total_loan_repayments_made_period total_loan_repayments_made_ytd total_loans_received_period total_loans_received_ytd total_offsets_to_operating_expenditures_period total_offsets_to_operating_expenditures_ytd total_operating_expenditures_period total_operating_expenditures_ytd total_receipts_period transfers_from_other_authorized_committee_period transfers_from_other_authorized_committee_ytd transfers_to_other_authorized_committee_period transfers_to_other_authorized_committee_ytd",
		"number|string[]": "amendment_chain",
		"string":          "amendment_indicator amendment_indicator_full beginning_image_number committee_id committee_name committee_type coverage_end_date coverage_start_date csv_url document_description end_image_number fec_file_id fec_url html_url means_filed pdf_url receipt_date report_form report_type report_type_full",
		"integer":         "cycle file_number report_year",
		"number|string":   "individual_itemized_contributions_period individual_itemized_contributions_ytd individual_unitemized_contributions_period individual_unitemized_contributions_ytd offsets_to_operating_expenditures_period offsets_to_operating_expenditures_ytd total_individual_contributions_period total_individual_contributions_ytd total_receipts_ytd",
		"boolean":         "is_amended most_recent",
	}),
	"/v1/reports/pac-party/": fieldsByKind(map[string]string{
		"number":          "all_loans_received_period all_loans_received_ytd allocated_federal_election_levin_share_period cash_on_hand_beginning_calendar_ytd cash_on_hand_beginning_period cash_on_hand_close_ytd cash_on_hand_end_period coordinated_expenditures_by_party_committee_period coordinated_expenditures_by_party_committee_ytd debts_owed_by_committee debts_owed_to_committee fed_candidate_committee_contribution_refunds_ytd fed_candidate_committee_contributions_period fed_candidate_committee_contributions_ytd fed_candidate_contribution_refunds_period independent_expenditures_period independent_expenditures_ytd loan_repayments_made_period loan_repayments_made_ytd loan_repayments_received_period loan_repayments_received_ytd loans_made_period loans_made_ytd most_recent_file_number net_contributions_period net_contributions_ytd net_operating_expenditures_period net_operating_expenditures_ytd non_allocated_fed_election_activity_period non_allocated_fed_election_activity_ytd nonfed_share_allocated_disbursements_period other_disbursements_period other_disbursements_ytd other_fed_operating_expenditures_period other_fed_operating_expenditures_ytd other_fed_receipts_period other_fed_receipts_ytd other_political_committee_contributions_period other_political_committee_contributions_ytd political_party_committee_contributions_period political_party_committee_contributions_ytd previous_file_number refunded_individual_contributions_period refunded_individual_contributions_ytd refunded_other_political_committee_contributions_period refunded_other_political_committee_contributions_ytd refunded_political_party_committee_contributions_period refunded_political_party_committee_contributions_ytd shared_fed_activity_nonfed_ytd shared_fed_activity_period shared_fed_activity_ytd shared_fed_operating_expenditures_period shared_fed_operating_expenditures_ytd shared_nonfed_operating_expenditures_period shared_nonfed_operating_expenditures_ytd subtotal_summary_page_period subtotal_summary_ytd total_contribution_refunds_period total_contribution_refunds_ytd total_contributions_period total_contributions_ytd total_disbursements_period total_disbursements_ytd total_fed_disbursements_period total_fed_disbursements_ytd total_fed_election_activity_period total_fed_election_activity_ytd total_fed_operating_expenditures_period total_fed_operating_expenditures_ytd total_fed_receipts_period total_fed_receipts_ytd total_nonfed_transfers_period total_nonfed_transfers_ytd total_operating_expenditures_period total_operating_expenditures_ytd total_receipts_period transfers_from_affiliated_party_period transfers_from_affiliated_party_ytd transfers_from_nonfed_account_period transfers_from_nonfed_account_ytd transfers_from_nonfed_levin_period transfers_from_nonfed_levin_ytd transfers_to_affiliated_committee_period transfers_to_affilitated_committees_ytd",
		"number|string[]": "amendment_chain",
		"string":          "amendment_indicator amendment_indicator_full beginning_image_number committee_id committee_name committee_type coverage_end_date coverage_start_date csv_url document_description end_image_number fec_file_id fec_url html_url means_filed pdf_url receipt_date report_form report_type report_type_full",
		"integer":         "calendar_ytd cycle file_number report_year",
		"number|string":   "individual_itemized_contributions_period individual_itemized_contributions_ytd individual_unitemized_contributions_period individual_unitemized_contributions_ytd offsets_to_operating_expenditures_period offsets_to_operating_expenditures_ytd total_individual_contributions_period total_individual_contributions_ytd total_receipts_ytd",
		"boolean":         "is_amended most_recent",
	}),
}

func fieldsByKind(groups map[string]string) map[string]string {
	out := make(map[string]string)
	for kind, fields := range groups {
		for _, field := range strings.Fields(fields) {
			out[field] = kind
		}
	}
	return out
}
